version: '3.3'

services:
  api:
    image: docker.io/library/python:latest
    restart: always

  db:
    image: mcr.microsoft.com/mssql/server:2017-latest
    ports:
      - "1433:1433"
    restart: always
    environment:
      HOMEBREW_NO_ENV_FILTERING: '1'
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: 'P@ssw0rd123'
